export const EMPRESA_REPOSITORY = 'EMPRESA_REPOSITORY';
export const TRANSFERENCIA_REPOSITORY = 'TRANSFERENCIA_REPOSITORY';
export const REGISTRAR_EMPRESA_USECASE = 'REGISTRAR_EMPRESA_USECASE';
export const LISTAR_ADHERIDAS_USECASE = 'LISTAR_ADHERIDAS_USECASE';
export const LISTAR_CON_TRANSFERENCIAS_USECASE = 'LISTAR_CON_TRANSFERENCIAS_USECASE';
